const beerStyles = [
  "-------- Select a Style ---------",
  "American Amber Ale",
  "American Amber Lager",
  "American Barley Wine",
  "American Black Ale",
  "American Brett",
  "American Brown Ale",
  "American Cream Ale",
  "American IPA",
  "American Imperial Porter",
  "American Imperial Red Ale",
  "American Imperial Stout",
  "American Lager",
  "American Pale Ale",
  "American Sour",
  "American Stout",
  "American Wheat",
  "American-Style Wheat Wine Ale",
  "Baltic-Style Porter",
  "Barrel-Aged Beer",
  "Belgian-Style Blonde Ale",
  "Belgian-Style Dubbel",
  "Belgian-Style Flanders",
  "Belgian-Style Fruit Lambic",
  "Belgian-Style Golden Strong Ale",
  "Belgian-Style Lambic/Gueuze",
  "Belgian-Style Pale Ale",
  "Belgian-Style Quadrupel",
  "Belgian-Style Saison",
  "Belgian-Style Tripel",
  "Belgian-Style Witbier",
  "Berliner-Style Weisse",
  "Blonde Ale",
  "Bohemian-Style Pilsener",
  "British-Style Barley Wine Ale",
  "California Common",
  "Chocolate Beer",
  "Coffee Beer",
  "Contemporary Gose",
  "English-Style Bitter",
  "English-Style Brown Ale",
  "English-Style Brown Porter",
  "English-Style IPA",
  "English-Style Mild",
  "English-Style Oatmeal Stout",
  "English-Style Old Ale",
  "English-Style Pale Ale (ESB)",
  "English-Style Sweet Stout (Milk Stout)",
  "European-Style Export",
  "French-Style Biere de Garde",
  "Fruit and Field Beer",
  "German-Style Altbier",
  "German-Style Bock",
  "German-Style Doppelbock",
  "German-Style Dunkel",
  "German-Style Dunkelweizen",
  "German-Style Hefeweizen",
  "German-Style Helles",
  "German-Style Kolsch",
  "German-Style Maibock",
  "German-Style Marzen / Oktoberfest",
  "German-Style Pilsner",
  "German-Style Schwarzbier",
  "German-Style Weizenbock",
  "Gluten-Free Craft Beer",
  "Herb and Spice Beer",
  "Honey Beer",
  "Imperial India Pale Ale",
  "Irish-Style Dry Stout",
  "Irish-Style Red Beer",
  "New England IPA",
  "Pumpkin Beer",
  "Robust Porter",
  "Rye Beer",
  "Scotch Ale/Wee Heavy",
  "Scottish-Style Ale",
  "Session Beer",
  "Smoke Beer",
  "Smoke Porter",
  "Specialty Beer",
  "Vienna-Style Lager",
];

export default beerStyles;
